### ISSUE TITLE
[littlelink-server] Cannot remove GitHub button

### ISSUE THREAD

**Issue by iMartyn** [samipsolutions/helm-charts#76]
### Helm chart name

littlelink-server

### Helm chart version

3.0.0

### Container name

irellevant

### Container tag

irellevant

### Description

By having a `GITHUB` env baked into the chart `values.yaml`, ArgoCD merges that with my values and adds a `GITHUB=` value.  If I set `GITHUB={}`, the pod definition is broken.  It's not possible to not have a github link on the page with this chart.

### Expected result

I expect to be able to define a set of values that doesn't include a github link for non-techies on their landing page.

### Helm values to reproduce

```YAML
env:
  TWITCH: https://twitch.tv/acapellawolf
  BUTTON_ORDER: TWITCH
```
